version: '3.7'

services:
  geth-bootnode:
    hostname: geth-bootnode
    container_name: bootnode
    env_file:
      - .env
    image: geth-client
    build:
      context: .
      args:
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    command: --nodekeyhex="<NODEKEYHEX>"
      --nodiscover
      --ipcdisable
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
    networks:
      priv-eth-net:
    expose:
      - '30303'

  geth-rpc-endpoint:
    hostname: geth-rpc-endpoint
    container_name: rpc-endpoint
    env_file:
      - .env
    image: geth-client
    depends_on:
      - geth-bootnode
    command: --bootnodes="enode://<ENODE_VALUE>@geth-bootnode:30303"
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,admin,personal"
      --http.corsdomain="*"
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
    ports:
      - '8545:8545'
    networks:
      priv-eth-net:
    expose:
      - '8545'

  geth-miner:
    hostname: geth-miner
    container_name: miner
    env_file:
      - .env
    image: geth-client
    depends_on:
      - geth-bootnode
    command: --bootnodes="enode://<ENODE_VALUE>@geth-bootnode:30303"
      --mine
      --miner.threads=1
      --networkid=${NETWORK_ID}
      --netrestrict="172.16.254.0/28"
    networks:
      priv-eth-net:
    expose:
      - '30303'

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor:latest
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    networks:
      priv-eth-net:
    expose:
      - '8080'

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      priv-eth-net:
    expose:
      - '9090'

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - '3000:3000'
    networks:
      priv-eth-net:

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.254.0/28
